gxt version 2.0: support to encrypt note

diff --git a/gxt b/gxt
--- a/gxt
+++ b/gxt
@@ -2,17 +2,20 @@
 # Giap Tran <txgvnn@gmail.com>
 # github.com/TxGVNN/gxt
 
-REPO=~/.gxt
+REPO="$HOME/.gxt"
+RC="$HOME/.gxtrc"
 DIR_WORK=$(pwd -P)
 
 _version(){
-	echo 'gxt "Xnote Git" version 1.0'
+	echo -e 'What is this? \tgxt "Xnote Git" 2.0'
 }
 
 _help(){
-	echo -e 'What is this? \tgxt "Xnote GiT"'
+	_version
 	echo ""
-	echo "commands are:"
+	echo "Usage: gxt COMMAND [OPTIONS] [ARGS..]"
+	echo ""
+	echo "Commands are:"
 	echo -e "\tnew \tNew or update note |edit|vi|update|"
 	echo -e "\tadd \tAdd file to note"
 	echo -e "\tsearch \tsearch note with name or content contain pattern |find|"
@@ -25,63 +28,145 @@ _help(){
 	echo -e "\tlist \tList all notes |ls|"
 	echo -e "\tlog \tlog all or only note"
 	echo ""
+	echo "Options are:"
+	echo -e "\t-g, --gpg		Encrypt notes with GnuPG"
+	echo -e "\t-m, --match		Search with match pattern"
+	echo -e "\t-v, --version	Show the version"
+	echo -e "\t-h, --help		Show this guide"
 	exit
 }
 
+_bootstrap(){
+	for opt in "$@"
+	do
+		if [[ "$opt" == [-]* ]]; then
+			long='';
+			case ${opt:1:1} in
+				g)	GPG=0 ;;
+				h)	HELP=0;;
+				v)	VERSION=0;;
+				c)	long="CATEGORY";;
+				m)	MATCH=0;
+					case ${opt:2} in
+						help) HELP=0;;
+						version) VERSION=0;;
+						category) long="CATEGORY";;
+					esac;;
+			esac
+		else
+			if [ "$long" ]; then
+				eval "$long"="$opt"
+			else
+				commands+="$IFS$opt"
+			fi
+		fi
+	done
+
+	if [ "$VERSION" ]; then
+		_version
+		exit
+	fi
+	if [ "$HELP" ]; then
+		_help
+	fi
+}
+_gpg_(){
+	if [ ! "$RECIPIENT" ]; then
+		echo "Please setup first: gxt gpg EMAIL|PUBKEYID"
+		exit 1
+	fi
+	# hook_close
+	if [ "$1" == "encrypt" ] && [ -f "$SRC" ]; then
+		gpg --yes --trust-model always --output "$GPG_TEXT" --encrypt --recipient "$RECIPIENT" "$SRC"
+		rm -rf "$SRC"
+		SRC="$GPG_TEXT"
+	fi
+	# hook_open
+	if [ "$1" == "decrypt" ]; then
+		if [ -z "$GPG_TMP" ]; then
+			GPG_TMP="$(mktemp -u -t .gxt-XXXXXX)"
+		fi
+		if [ -f "$SRC" ] && file "$SRC" | grep PGP -q; then
+			gpg --output "$GPG_TMP" --decrypt "$SRC"
+		else
+			cp "$SRC" "$GPG_TMP"
+		fi
+		GPG_TEXT="$SRC"
+		SRC="$GPG_TMP"
+	fi
+}
+
+_hook_open(){
+	if [ "$GPG" ]; then
+		_gpg_ "decrypt"
+	fi
+}
+
+_hook_close(){
+	if [ "$GPG" ]; then
+		_gpg_ "encrypt"
+	fi
+}
+
 _init(){
+	if [ -f "$RC" ]; then
+		# shellcheck disable=SC1090
+		. "$RC"
+	else
+		echo 'RECIPIENT='>> "$RC"
+	fi
 	if [ ! -d "$REPO/.git" ]; then
 		git init "$REPO" > /dev/null
 	fi
 }
 
-_new(){
-	if [ "$#" -eq 2 ];then
-		if [ -f "$REPO/$2" ]; then
-			_edit "$@"
-			exit
-		else
-			if [[ "$2" == *[/]* ]]; then
-				dir=${2%/*}
-				mkdir -p "$REPO/$dir"
-			fi
-			editor "$REPO/$2"
-		fi
-
-
-		if [ -n "$(git status -s | awk '/??/ || /M/')" ]; then
-			git add "$2"
-			git commit -m "Add $2" | head -n1
-		fi
-	else
-		echo "gxt new <note-name>"
-		echo "gxt vi <note-name>"
+_gpg_setup(){
+	if [ ! "$SRC" ]; then
+		echo "gxt gpg EMAIl|PUBKEYID"
+		echo "Example:"
+		echo " gxt gpg txgvnn@gmail.com"
+		exit 1
 	fi
+	if ! which gpg; then
+		echo "Please install gnupg tools first"
+		exit 1
+	fi
+	gpg --search-keys "$SRC"
+	pubkey="$(gpg --list-public-keys "$SRC" | awk '/pub/ {print $2}' | grep  -oE '0[a-zA-Z].*?')"
+	sed -i 's/RECIPIENT=.*/RECIPIENT='"$pubkey"'/g' "$RC"
 }
 
 _edit(){
-	if [ "$#" -eq 2 ];then
-		if [ -f "$REPO/$2" ]; then
-			editor "$REPO/$2"
-			if [ -n "$(git status -s | awk '/??/ || /M/')" ]; then
-				git add "$2"
-				git commit -m "Update $2" | head -n1
-			fi
-		else
-			printf 'Note "%s" not found' "$2"
-		fi
+	msg="Update "
+	if [ ! "$SRC" ]; then
+		echo "gxt new NOTE [-g|--gpg]"
+		echo "gxt vi NOTE [-g|--gpg]"
+	fi
 
-	else
-		echo "gxt vi <note-name>"
-		echo "gxt edit <note-name>"
-		echo "gxt update <note-name>"
+	if [ ! -f "$SRC" ]; then
+		if [[ "$SRC" == *[/]* ]]; then
+			dir=${SRC%/*}
+			mkdir -p "$dir"
+		fi
+		msg="Add "
+	fi
+
+	_hook_open
+	editor "$SRC"
+	_hook_close
+
+	if [ -n "$(git status -s | awk '/??/ || /M/')" ]; then
+		git add "$SRC"
+		git commit -m "${msg} ${SRC}" | head -n1
 	fi
 }
 
 _add(){
-	if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
-		echo "gxt add <file> [<new-note-name]"
+	if [ ! "$SRC" ]; then
+		echo "gxt add <file> NEW-NOTE [-g|--gpg]"
+		exit 1
 	else
-		if [ -f "$3" ]; then
+		if [ -f "$DEST" ]; then
 			printf "Note has exist. Do you want override that (y/N)? "
 			read -r override
 			if [[ "$override" != "y" && "$override" != "Y" ]]; then
@@ -89,21 +174,23 @@ _add(){
 			fi
 		fi
 
-		notes=$3
-		if [ -z "$3" ]; then
-			notes=${2##*/}
+		notes=$DEST
+		if [ -z "$notes" ]; then
+			notes=${SRC##*/}
 		fi
 		#if need to create new directory
-		if [[ "$3" == *[/]* ]]; then
-			dir=${3%/*}
-			mkdir -p "$REPO/$dir"
+		if [[ "$DEST" == *[/]* ]]; then
+			dir=${DEST%/*}
+			mkdir -p "$dir"
 		fi
 
-		if [[ "$2" == /* ]]; then
-			cp "$2" "$REPO/$notes"
-		else
-			cp "$DIR_WORK/$2" "$REPO/$notes"
+		if [[ "$SRC" != /* ]]; then
+			SRC="$DIR_WORK/$SRC"
 		fi
+		_hook_open
+		cp "$SRC" "$notes"
+		GPG_TEXT="$notes"
+		_hook_close
 
 		if [ -n "$(git status -s | awk '/^\?\?/ || /^ M/')" ]; then
 			git add "$notes"
@@ -116,118 +203,103 @@ _add(){
 }
 
 _view(){
-	if [ "$#" -ne 2 ];then
-		echo "gxt cat <note-name>"
-		echo "gxt less <note-name>"
-		echo "gxt more <note-name>"
-	else
-		case $1 in
-			less)
-				less "$2"
-				;;
-			more)
-				more "$2"
-				;;
-			*)
-				cat "$2"
-				;;
-		esac
+	if [ ! "$SRC" ];then
+		echo "gxt cat NOTE"
+		echo "gxt less NOTE"
+		echo "gxt more NOTE"
+		exit 1
 	fi
+	_hook_open
+	case "$com" in
+		less)
+			less "$SRC"
+			;;
+		more)
+			more "$SRC"
+			;;
+		*)
+			cat "$SRC"
+			;;
+	esac
+	_hook_close
 }
 
 _stat(){
-	if [ "$#" -ne 2 ];then
-		echo "gxt stat <note-name>"
-	else
-		stat "$2"
+	if [ ! "$SRC" ];then
+		echo "gxt stat NOTE"
+		exit 1
 	fi
+	stat "$2"
 }
 
 _list(){
+	if [ -n "$SRC" ] && [ ! -d "$SRC" ]; then
+		printf '"%s" is not category' "$SRC"
+		exit 1
+	fi
 	echo "# CATEGORIES"
-	find "./$2" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sed '/\.git/d'
+	find "./$SRC" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sed '/\.git/d'
 	echo ""
 	echo "# GLOBAL"
-	find "./$2" -mindepth 1 -maxdepth 1 -type f -exec basename {} \;
+	find "./$SRC" -mindepth 1 -maxdepth 1 -type f -exec basename {} \;
 }
 
 _search(){
-	content='';
+	if [ ! "$SRC" ]; then
+		echo "gxt find [-c category] [-m|--match] NAME|PATTERN"
+		exit 1
+	fi
 	dir='.'
-	while [[ $# -gt 0 ]]
-	do
-		key="$1"
-		case $key in
-			-c|--category)
-				dir="$2"
-				shift # past argument
-				;;
-			-h|--help)
-				echo "gxt find [-c category] [<like-name>] [ -- <pattern>]"
-				exit
-				;;
-			--)
-				content="0";
-				;;
-			*)
-				value="$1"
-				;;
-		esac
-		shift # past argument or value
-	done
-	[ -z "$value" ] && _search -h
-
-	if [ -n "$content" ] ; then
-		find "$dir"  -path ./.git -prune -o -type f -exec grep -n --color=always "$value" /dev/null {} + | sed -e 's,\./,,'
+	if [ "$CATEGORY" ]; then
+		dir="$CATEGORY"
+	fi
+	if [ "$MATCH" ] ; then
+		find "$dir"  -path ./.git -prune -o -type f -exec grep -n --color=always "$SRC" /dev/null {} + | sed -e 's,\./,,'
 	else
-		find "$dir" -path ./.git -prune -o -type f -printf '%P\0'  | grep -zi --color=always "$value" | tr \\0 \\n
+		find "$dir" -path ./.git -prune -o -type f -printf '%P\0'  | grep -zi --color=always "$SRC" | tr \\0 \\n
 	fi
 
 }
 
 _log(){
-	if [ "$#" -eq 1 ]; then
+	if [ ! "$SRC" ]; then
 		git log --graph --decorate --pretty=oneline --abbrev-commit
 	else
-		if [ "$#" -eq 2 ]; then
-			git  log --graph --decorate --pretty=oneline --abbrev-commit -- "$2"
-		else
-			echo "gxt log [note-name]"
-		fi
+		git  log --graph --decorate --pretty=oneline --abbrev-commit -- "$SRC"
 	fi
 }
 
 _share(){
-	if [ "$#" -ne 2 ];then
-		echo "gxt share <note-name>"
+	if [ ! "$SRC" ]; then
+		echo "gxt share NOTE [-g|--gpg]"
 	else
+		_hook_open
 		# can use pastebinit
-		<"$2" nc termbin.com 9999
+		<"$SRC" nc termbin.com 9999
+		_hook_close
 	fi
 }
 
 _move(){
-	if [ "$#" -ne 3 ] ;then
-		echo "gxt mv <old-notes> <new-notes>"
+	if [ ! "$SRC" ] && [ ! "$DEST" ] ;then
+		echo "gxt mv OLD_NOTE NEW_NOTE"
 	else
-		if [[ "$3" == *[/]* ]]; then
-			dir=${3%/*}
+		if [[ "$DEST" == *[/]* ]]; then
+			dir=${DEST%/*}
 			mkdir -p "$REPO/$dir"
 		fi
-		mv "$2" "$3"
+		mv "$SRC" "$DEST"
 		if [ -n "$(git status -s | awk '/^ D/')" ]; then
 			git add -u
-			git add "$3"
-			git commit -m "Rename $2 -> $3" | head -n1
-			git push origin master
+			git add "$DEST"
+			git commit -m "Rename $SRC -> $DEST" | head -n1
 		fi
-
 	fi
 }
 
 _remove(){
 	if [ "$#" -eq 1 ];then
-		echo "gxt rm <name-notes> ..."
+		echo "gxt rm NOTE..."
 	else
 		item=""
 		shift
@@ -237,7 +309,7 @@ _remove(){
 				rm -vrf "$note"
 				item+="$note "
 			else
-				printf 'not found %s\n' "$note"
+				printf 'Not found %s\n' "$note"
 			fi
 		done
 
@@ -250,82 +322,88 @@ _remove(){
 }
 
 _export(){
-	if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
-		echo "gxt export <name-notes> [PATH]"
+	if [ ! "$SRC" ] && [ ! "$DEST" ] ;then
+		echo "gxt export NOTE [PATH] [-g|--gpg]"
 	else
-		path=$3
-		if [ -z "$path" ]; then
-			path="$DIR_WORK"
+		path="$DIR_WORK"
+		if [ "$DEST" ]; then
+			path="$DEST"
 		fi
-		if [[ "$3" != /* ]]; then
+		if [[ "$DEST" != /* ]]; then
 			path="$DIR_WORK/$3"
 		fi
 
-		cp "$REPO/$2" "$path" -i
+		_hook_open
+		cp "$SRC" "$path" -i
+		_hook_close
 	fi
 
 }
 
-## __RUN__ ##
+_main(){
+	com="$1"
+	SRC="$2"
+	DEST="$3"
+	case "$com" in
+		new|vi|edit|update|nano)
+			_edit "$@"
+			;;
+
+		add)
+			_add "$@"
+			;;
+
+		cat|less|more)
+			_view "$@"
+			;;
+
+		stat)
+			_stat "$@"
+			;;
+
+		list|ls)
+			_list "$@"
+			;;
+
+		find|search)
+			_search "$@"
+			;;
+
+		export)
+			_export "$@"
+			;;
+
+		share)
+			_share "$@"
+			;;
+
+		mv|rename)
+			_move "$@"
+			;;
+
+		rm|remove|delete)
+			_remove "$@"
+			;;
+
+		log)
+			_log "$@"
+			;;
+
+		gpg)
+			_gpg_setup "$@"
+			;;
+
+		*)
+			_help
+			;;
+	esac
+}
+
 _init
+
+_bootstrap "$@"
 
 cd "$REPO" || exit 1
 
-case $1 in
-	new|vi)
-		_new "$@"
-		;;
-
-	edit|update)
-		_edit "$@"
-		;;
-
-	add)
-		_add "$@"
-		;;
-
-	cat|less|more)
-		_view "$@"
-		;;
-
-	stat)
-		_stat "$@"
-		;;
-
-	list|ls)
-		_list "$@"
-		;;
-
-	find|search)
-		shift
-		_search "$@"
-		;;
-
-	export)
-		_export "$@"
-		;;
-
-	share)
-		_share "$@"
-		;;
-
-	mv|rename)
-		_move "$@"
-		;;
-
-	rm|remove|delete)
-		_remove "$@"
-		;;
-
-	log)
-		_log "$@"
-		;;
-
-	--version)
-		_version
-		;;
-
-	*)
-		_help
-		;;
-esac
+#shellcheck disable=2086
+_main $commands
